# Setup
title:        Edge-Device Large Language Model Competition
description: NeurIPS 2024 Challenge
baseurl:      "/edge-llm-challenge.github.io"
paginate:     1
locale:       "en"

# About/contact
author:
  #name:       Author name
  url:       "https://edge-llms-challenge.github.io" 

#Others
navigation:
  Home: "index"
  Challenge: "challenge"
  Rules: "rules"
  Timeline: "dates"
  Prizes: "prizes"
  Starting Kit: "starter_kit"
  Registration: "registration"
  Feedback: "feedback"
  Leaderboard: "leaderboard"
  Organizers: "organizers"
  #Advisors: "advisors"
  Workshop: "schedule"
  Sponsors: "sponsors"
  Q&A: "question"
markdown: kramdown